import { createApp } from 'vue'
import {
  ElAside,
  ElButton,
  ElCheckbox,
  ElCheckboxGroup,
  ElCol,
  ElContainer,
  ElDatePicker,
  ElDrawer,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElIcon,
  ElInput,
  ElMain,
  ElMenu,
  ElMenuItem,
  ElOption,
  ElPagination,
  ElRadioButton,
  ElRadioGroup,
  ElRow,
  ElSegmented,
  ElSelect,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElTabPane,
  ElTabs,
  ElTag,
} from 'element-plus'
import 'element-plus/dist/index.css'
import {
  ArrowDown,
  ArrowUp,
  Calendar,
  Clock,
  Coin,
  DataAnalysis,
  DataLine,
  EditPen,
  Histogram,
  List,
  Money,
  Reading,
  Refresh,
  Search,
  TopRight,
  Warning,
} from '@element-plus/icons-vue'
import App from './App.vue'
import router from './router'

const app = createApp(App)
const icons = {
  ArrowDown,
  ArrowUp,
  Calendar,
  Clock,
  Coin,
  DataAnalysis,
  DataLine,
  EditPen,
  Histogram,
  List,
  Money,
  Reading,
  Refresh,
  Search,
  TopRight,
  Warning,
}
const components = [
  ElAside,
  ElButton,
  ElCheckbox,
  ElCheckboxGroup,
  ElCol,
  ElContainer,
  ElDatePicker,
  ElDrawer,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElIcon,
  ElInput,
  ElMain,
  ElMenu,
  ElMenuItem,
  ElOption,
  ElPagination,
  ElRadioButton,
  ElRadioGroup,
  ElRow,
  ElSegmented,
  ElSelect,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElTabPane,
  ElTabs,
  ElTag,
]

app.use(router)
components.forEach(component => app.component(component.name, component))
Object.entries(icons).forEach(([key, component]) => app.component(key, component))
app.mount('#app')
